---
- name: Setup Dev Workstation on Ubuntu
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Atualizar cache do APT
      apt:
        update_cache: yes

    - name: Instalar pacotes via APT
      apt:
        name:
          - vim
          - htop
          - tree
          - snapd
          - gdebi
          - python3-pip
          - curl
          - gnupg
          - lsb-release
          - jq
          - remmina
          - flameshot
          - virtualbox
          - tilix
          - zsh
          - obs-studio
        state: present

    # Docker
    - name: Adicionar chave GPG do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Adicionar usuário ao grupo docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    # Terraform
    - name: Instalar Terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
        dest: /usr/local/bin/
        remote_src: yes
        creates: /usr/local/bin/terraform

    # Helm
    - name: Instalar Helm
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
      args:
        chdir: /tmp

    # Kind
    - name: Instalar Kind
      get_url:
        url: https://github.com/kubernetes-sigs/kind/releases/latest/download/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: '0755'

    # kubectx e kubens
    - name: Instalar kubectx e kubens
      shell: |
        git clone https://github.com/ahmetb/kubectx /opt/kubectx
        ln -sf /opt/kubectx/kubens /usr/local/bin/kubens
        ln -sf /opt/kubectx/kubectx /usr/local/bin/kubectx

